version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: interview
    ports:
      - "3050:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: app_container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://root:@db:3306/interview"

volumes:
  mysql_data:
